//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyWebClient.CompanyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompanyService.ICompanyProvidedPublicService")]
    public interface ICompanyProvidedPublicService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyProvidedPublicService/CompanyPublicService", ReplyAction="http://tempuri.org/ICompanyProvidedPublicService/CompanyPublicServiceResponse")]
        string CompanyPublicService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyProvidedPublicService/CompanyPublicService", ReplyAction="http://tempuri.org/ICompanyProvidedPublicService/CompanyPublicServiceResponse")]
        System.Threading.Tasks.Task<string> CompanyPublicServiceAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICompanyProvidedPublicServiceChannel : CompanyWebClient.CompanyService.ICompanyProvidedPublicService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompanyProvidedPublicServiceClient : System.ServiceModel.ClientBase<CompanyWebClient.CompanyService.ICompanyProvidedPublicService>, CompanyWebClient.CompanyService.ICompanyProvidedPublicService {
        
        public CompanyProvidedPublicServiceClient() {
        }
        
        public CompanyProvidedPublicServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompanyProvidedPublicServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyProvidedPublicServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyProvidedPublicServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CompanyPublicService() {
            return base.Channel.CompanyPublicService();
        }
        
        public System.Threading.Tasks.Task<string> CompanyPublicServiceAsync() {
            return base.Channel.CompanyPublicServiceAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompanyService.ICompanyProvidedConfidentialService")]
    public interface ICompanyProvidedConfidentialService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyProvidedConfidentialService/CompanyConfidentialService" +
            "", ReplyAction="http://tempuri.org/ICompanyProvidedConfidentialService/CompanyConfidentialService" +
            "Response")]
        string CompanyConfidentialService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyProvidedConfidentialService/CompanyConfidentialService" +
            "", ReplyAction="http://tempuri.org/ICompanyProvidedConfidentialService/CompanyConfidentialService" +
            "Response")]
        System.Threading.Tasks.Task<string> CompanyConfidentialServiceAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICompanyProvidedConfidentialServiceChannel : CompanyWebClient.CompanyService.ICompanyProvidedConfidentialService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompanyProvidedConfidentialServiceClient : System.ServiceModel.ClientBase<CompanyWebClient.CompanyService.ICompanyProvidedConfidentialService>, CompanyWebClient.CompanyService.ICompanyProvidedConfidentialService {
        
        public CompanyProvidedConfidentialServiceClient() {
        }
        
        public CompanyProvidedConfidentialServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompanyProvidedConfidentialServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyProvidedConfidentialServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyProvidedConfidentialServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CompanyConfidentialService() {
            return base.Channel.CompanyConfidentialService();
        }
        
        public System.Threading.Tasks.Task<string> CompanyConfidentialServiceAsync() {
            return base.Channel.CompanyConfidentialServiceAsync();
        }
    }
}
